contact_links:
    - name: 📃 Documentation Issue
      url: https://github.com/c-code-x/codex-website/issues/new
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
    - name: 🤔 Questions and Help
      url: https://github.com/orgs/c-code-x/discussions
      about: This issue tracker is not for support questions. Please refer to the Codex community's help and discussion forums.
